# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme: "ocean"   #"minimal" "1950s" "coffee" "forest"  "mrrobot" "apogee" "dark" "ocean" "rose" "strawberry"

  # Enable users to switch between day and night mode?
  day_night: true

  #theme_day: minimal
  #theme_night: minimal
  # Choose a font size.
  # Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: 'wowchemy'
  analytics:
    google_analytics: 'UA-98320547-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter: 
    enable: true
    extra_languages:
      - r
      - latex
      - python
  math:
    enable: true #false
  diagram:
    enable: true #false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/Kwabena-Moore/starter-hugo-academic'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true

